#define NUMSTEPS 8
#define NUMVOICES 8
#define NEOPIXEL_PIN 39
#define POTI_PIN 40
#define BUTTON_PIN 41

#define LED_SIG_PIN 36
#define LED_SELECT_0_PIN 24
#define LED_SELECT_1_PIN 25
#define LED_SELECT_2_PIN 26
#define LED_SELECT_3_PIN 27

#define HALL_A_SELECT_0_PIN 28
#define HALL_A_SELECT_1_PIN 29
#define HALL_A_SELECT_2_PIN 30
#define HALL_A_SELECT_3_PIN 31

#define HALL_B_SELECT_0_PIN 32
#define HALL_B_SELECT_1_PIN 33
#define HALL_B_SELECT_2_PIN 34
#define HALL_B_SELECT_3_PIN 35

#define HALL_A_SIG_PIN 38
#define HALL_B_SIG_PIN 37

#define CC_ACCELERATION_X 10
#define CC_ACCELERATION_Y 20

